ALTER TABLE "Job" ALTER COLUMN "careerId" DROP NOT NULL;
ALTER TABLE "Job" DROP CONSTRAINT IF EXISTS "Job_careerId_fkey";
ALTER TABLE "Job" ADD CONSTRAINT "Job_careerId_fkey"
  FOREIGN KEY ("careerId") REFERENCES "Career"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Job" ADD COLUMN "courseId" INTEGER;
CREATE INDEX "Job_courseId_idx" ON "Job"("courseId");
ALTER TABLE "Job" ADD CONSTRAINT "Job_courseId_fkey"
  FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE SET NULL ON UPDATE CASCADE;
